version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt install jq -y
      - run:
          name: Stop Scan ðŸ›‘
          command: |
              nexploit-cli scan:stop --token $NEXPLOIT_TOKEN ${SCAN_ID}
                #We send a curl request to get all the scan issues and after that we parse the Id with jq
                GET_ID=$(curl -X 'GET' 'https://app.neuralegion.com/api/v1/scans/'$SCAN_ID'/issues' -H 'accept: application/json' \
                -H 'Authorization: Api-Key 'lfjlqct.nexa.63fphe9ajwm60vxjb2fluxaczs68sj5b'' | jq '.[].id' )
                #We delete "(quotation marks) and insert all ids into the new array  
                ISSUES_ID_ARRAY=$(sed -e 's/^"//' -e 's/"$//' <<<"$GET_ID")
                #We insert everything from a previously made array into a new array(a), and for each value we give index value
                a=(); while read -r line; do a+=("$line"); done <<<"$ISSUES_ID_ARRAY"; declare a;

                GET_NAME=$(curl -X 'GET' 'https://app.neuralegion.com/api/v1/scans/'$SCAN_ID'/issues' \
                 -H 'accept: application/json' -H 'Authorization: Api-Key 'lfjlqct.nexa.63fphe9ajwm60vxjb2fluxaczs68sj5b'' | jq '.[].name' )
                ISSUES_NAME_ARRAY=$(sed -e 's/^"//' -e 's/"$//' <<<"$GET_NAME")
                b=(); while read -r line; do b+=("$line"); done <<<"$ISSUES_NAME_ARRAY"; declare b;

                GET_DETAILS=$(curl -X 'GET' 'https://app.neuralegion.com/api/v1/scans/'$SCAN_ID'/issues'  \
                -H 'accept: application/json' -H 'Authorization: Api-Key 'lfjlqct.nexa.63fphe9ajwm60vxjb2fluxaczs68sj5b'' | jq '.[].details' )
                ISSUES_DETAILS_ARRAY=$(sed -e 's/^"//' -e 's/"$//' <<<"$GET_DETAILS")
                c=(); while read -r line; do c+=("$line"); done <<<"$ISSUES_DETAILS_ARRAY"; declare c;

                GET_SEVERITY=$(curl -X 'GET' 'https://app.neuralegion.com/api/v1/scans/'$SCAN_ID'/issues' -H 'accept: application/json' \ 
                -H 'Authorization: Api-Key 'lfjlqct.nexa.63fphe9ajwm60vxjb2fluxaczs68sj5b'' | jq '.[].severity' )
                ISSUES_SEVERITY_ARRAY=$(sed -e 's/^"//' -e 's/"$//' <<<"$GET_SEVERITY")
                d=(); while read -r line; do d+=("$line"); done <<<"$ISSUES_SEVERITY_ARRAY"; declare d;

                GET_PROTOCOL=$(curl -X 'GET' 'https://app.neuralegion.com/api/v1/scans/'$SCAN_ID'/issues' \ 
                -H 'accept: application/json' -H 'Authorization: Api-Key 'lfjlqct.nexa.63fphe9ajwm60vxjb2fluxaczs68sj5b'' | jq '.[].protocol' )
                ISSUES_PROTOCOL_ARRAY=$(sed -e 's/^"//' -e 's/"$//' <<<"$GET_PROTOCOL")
                e=(); while read -r line; do e+=("$line"); done <<<"$ISSUES_PROTOCOL_ARRAY"; declare e;

                GET_EXPOSURE=$(curl -X 'GET' 'https://app.neuralegion.com/api/v1/scans/'$SCAN_ID'/issues' \
                -H 'accept: application/json' -H 'Authorization: Api-Key 'lfjlqct.nexa.63fphe9ajwm60vxjb2fluxaczs68sj5b'' | jq '.[].exposure' )
                ISSUES_EXPOSURE_ARRAY=$(sed -e 's/^"//' -e 's/"$//' <<<"$GET_EXPOSURE")
                f=(); while read -r line; do f+=("$line"); done <<<"$ISSUES_EXPOSURE_ARRAY"; declare f;

                GET_CVSS=$(curl -X 'GET' 'https://app.neuralegion.com/api/v1/scans/'$SCAN_ID'/issues' \ 
                -H 'accept: application/json' -H 'Authorization: Api-Key 'lfjlqct.nexa.63fphe9ajwm60vxjb2fluxaczs68sj5b'' | jq '.[].cvss' )
                ISSUES_CVSS_ARRAY=$(sed -e 's/^"//' -e 's/"$//' <<<"$GET_CVSS")
                g=(); while read -r line; do g+=("$line"); done <<<"$ISSUES_CVSS_ARRAY"; declare g;

                GET_CWE=$(curl -X 'GET' 'https://app.neuralegion.com/api/v1/scans/'$SCAN_ID'/issues'  \
                -H 'accept: application/json' -H 'Authorization: Api-Key 'lfjlqct.nexa.63fphe9ajwm60vxjb2fluxaczs68sj5b'' | jq '.[].cwe' )
                ISSUES_CWE_ARRAY=$(sed -e 's/^"//' -e 's/"$//' <<<"$GET_CWE")
                h=(); while read -r line; do h+=("$line"); done <<<"$ISSUES_CWE_ARRAY"; declare h;

                GET_TIME=$(curl -X 'GET' 'https://app.neuralegion.com/api/v1/scans/'$SCAN_ID'/issues' \ 
                -H 'accept: application/json' -H 'Authorization: Api-Key 'lfjlqct.nexa.63fphe9ajwm60vxjb2fluxaczs68sj5b'' | jq '.[].time' )
                ISSUES_TIME_ARRAY=$(sed -e 's/^"//' -e 's/"$//' <<<"$GET_TIME")
                j=(); while read -r line; do i+=("$line"); done <<<"$ISSUES_TIME_ARRAY"; declare j;

                echo "The number of issues we found is is ${#a[*]}"
                len=${#a[*]}
                i=0
                while [ $i -lt $len ]; do
                echo " "
                echo " "
                echo "ID OF THE SCAN IS    ${a[$i]}"
                echo "NAME    "${b[$i]}
                echo "DETAILS    "${c[$i]}
                echo "SEVERITY    "${d[$i]}
                echo "PROTOCOL    "${e[$i]}
                echo "EXPOSURE    "${f[$i]}
                echo "CVSS    "${g[$i]}
                echo "CWE    "${h[$i]}
                echo "TIME    "${j[$i]}
                let i=i+1
                done

